# Generated by Django 5.2.7 on 2025-11-05 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('register_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('register_image', models.ImageField(blank=True, null=True, upload_to='cropped/register/')),
                ('subject_image', models.ImageField(blank=True, null=True, upload_to='cropped/subject/')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('uploading', 'Uploading to LMS'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('temp_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'PDF Upload',
                'verbose_name_plural': 'PDF Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
