# Generated by Django 5.2.7 on 2025-11-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='mongodb_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
