# Generated by Django 5.2.7 on 2025-11-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0002_pdfupload_is_uploaded_pdfupload_mongodb_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfupload',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='pdfupload',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='register_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
